[package]
name = "treasure"
version = "0.0.2"
authors = ["Peter Vrba <phonkee@phonkee.eu>"]
description = "Treasure ORM - object relational mapper for rust language"

[lib]
name = "treasure"
plugin = true
path = "src/lib.rs"