use super::options::ModelOptions;
use super::columns::options;


// Model trait
pub trait Model {

	// returns model options such as table name, list of all columns with info.
	// concrete implementation will be generated by treasure.
	// this method could be possibli inlined??
	fn model_options(&self) -> ModelOptions;

	// init function to create new model instance.
	fn init_new() -> Self;

	// column_info returns information about column (calls options method and finds appropriate ColumnInfo)
	fn column_options(column:String) -> Option<options::Options>;
}